name: "Compiling my business-card while pushing a new tag"
on:
  push:
    tags:
      - v1.**
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: xelatex card.tex
