name: "Deploy to GAE"
on:
  push:
    tags:
      - v1.**
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Compile Business card
      - uses: actions/checkout@v2
        run: xelatex card.tex
