name: "Deploy to GAE"
on:
  push:
    tags:
      - v1.**
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
